app_type: nodejs
branch: main
build_command: pnpm run build
build_dir: ./
crate_name: null
database: null
environment:
  ATHENA_ADMIN_EXPERIMENTAL_ENABLED: ${ATHENA_ADMIN_EXPERIMENTAL_ENABLED}
  ATHENA_API_KEY: ${ATHENA_API_KEY}
  ATHENA_AVAILABLE_CLIENTS: ${ATHENA_AVAILABLE_CLIENTS}
  ATHENA_CLIENT: ${ATHENA_CLIENT}
  NPM_TOKEN: ${NPM_TOKEN}
  READ_ONLY: ${READ_ONLY}
github: null
install_command: pnpm install
kafka_brokers: null
kafka_public_url: null
kafka_topic: null
linear:
  release:
    initiative_ids:
    - fd28f67f-8dc8-44b2-bf14-3821ce389145
    organization_name: ${LINEAR_ORG_NAME}
log_files: null
monitor_expected_code: null
monitor_interval: null
monitor_method: null
monitor_url: null
npm_script: null
port: 4000
port_storybook: null
project_name: '@xylex-group/athena-mcp'
publish:
  npm:
    access: public
    enabled: true
    generate_npmrc: true
    manifest_path: package.json
    package_name: '@xylex-group/athena-mcp'
    preflight_commands:
    - pnpm test
    publish_command: npm publish
    token: ${NPM_TOKEN}
    use_wsl: false
    working_directory: ./
    wsl_distribution: null
services:
- branch: main
  commands:
    build: pnpm run build
    dev: null
    install: pnpm install
    pre: null
    start: pnpm run node
  environment:
    ATHENA_ADMIN_EXPERIMENTAL_ENABLED: ${ATHENA_ADMIN_EXPERIMENTAL_ENABLED}
    ATHENA_API_KEY: ${ATHENA_API_KEY}
    ATHENA_AVAILABLE_CLIENTS: ${ATHENA_AVAILABLE_CLIENTS}
    ATHENA_CLIENT: ${ATHENA_CLIENT}
    NPM_TOKEN: ${NPM_TOKEN}
    READ_ONLY: ${READ_ONLY}
  force_run_from_root: false
  healthcheck_path: null
  name: '@xylex-group/athena-mcp'
  port: 3000
  restart_policy: on_failure
  restart_policy_max_failure_count: 10
  root_directory: ./
  start_wrapper: pm2
  systemd: null
  systemd_service_name: null
  target: nodejs
  url: null
  version_targets:
  - package.json
start_command: pnpm run node
systemd: null
systemd_service_name: null
target: nodejs
url: null
url_storybook: null
version: 0.4.2
version_targets:
- package.json
